# Generated by Django 4.1.5 on 2023-02-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApi', '0003_alter_task_date_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
